package POJO;
// Generated Oct 26, 2020 5:52:23 PM by Hibernate Tools 4.3.1

import DAO.DAOorder;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;




/**
 * TblOrder generated by hbm2java
 */
@ManagedBean
public class TblOrder  implements java.io.Serializable {


     private Integer idOrder;
     private String namaUser;
     private int idRoom;
     private String checkIn;
     private String checkOut;

    public String getTanggal() {
        return tanggal;
    }

    public void setTanggal(String tanggal) {
        this.tanggal = tanggal;
    }

    public String getBulan() {
        return bulan;
    }

    public void setBulan(String bulan) {
        this.bulan = bulan;
    }

    public String getTahun() {
        return tahun;
    }

    public void setTahun(String tahun) {
        this.tahun = tahun;
    }
     private String tanggal;
     private String bulan;
     private String tahun;
     
      public String save_order()
     {
         
         
         String tanggal,bulan,tahun;
         tanggal = this.tanggal;
         bulan = this.bulan;
         tahun = this.tahun;
         checkIn = tanggal+"/"+bulan+"/"+tahun;
         checkOut = tanggal+"/"+bulan+"/"+tahun;
         DAOorder add = new DAOorder();
         add.add_order(this);
         return "thankyou";
     } 
      
     public List<SelectItem> getAllRoom(){
        List<SelectItem> admin = new ArrayList<>();
        DAOorder controller = new DAOorder();
        List<TblRoom> adminID = controller.retrieveRoom();
         for(TblRoom kode: adminID){
            admin.add(new SelectItem(kode.getIdRoom(), kode.getNamaRoom()));
        }
        return admin;
    } 
      
    public TblOrder() {
    }

	
    public TblOrder(int idRoom) {
        this.idRoom = idRoom;
    }
    public TblOrder(String namaUser, int idRoom, String checkIn, String checkOut) {
       this.namaUser = namaUser;
       this.idRoom = idRoom;
       this.checkIn = checkIn;
       this.checkOut = checkOut;
    }
   
    public Integer getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }
    public String getNamaUser() {
        return this.namaUser;
    }
    
    public void setNamaUser(String namaUser) {
        this.namaUser = namaUser;
    }
    public int getIdRoom() {
        return this.idRoom;
    }
    
    public void setIdRoom(int idRoom) {
        this.idRoom = idRoom;
    }
    
    public String getCheckIn() {
        return this.checkIn;
    }
    
    public void setCheckIn(String checkIn) {
        this.checkIn = checkIn;
    }
    public String getCheckOut() {
        return this.checkOut;
    }
    
    public void setCheckOut(String checkOut) {
        this.checkOut = checkOut;
    }




}


